"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.READER_SETTINGS_DEFAULTS = exports.IPC_CHANNELS = void 0;
exports.IPC_CHANNELS = {
    ping: 'app:ping',
    discoverSearch: 'discover:search',
    discoverDownload: 'discover:download',
    booksList: 'books:list',
    booksAddSample: 'books:add-sample',
    booksImport: 'books:import',
    booksReveal: 'books:reveal',
    booksDelete: 'books:delete',
    booksGetPdfData: 'books:get-pdf-data',
    booksGetEpubData: 'books:get-epub-data',
    booksGetFb2Data: 'books:get-fb2-data',
    booksGetTxtData: 'books:get-txt-data',
    notesCreate: 'notes:create',
    notesList: 'notes:list',
    notesDelete: 'notes:delete',
    notesUpdate: 'notes:update',
    highlightsList: 'highlights:list',
    highlightsCreateMerged: 'highlights:create-merged',
    highlightsDelete: 'highlights:delete',
    highlightsInsertRaw: 'highlights:insert-raw',
    highlightsUpdateNote: 'highlights:update-note',
    epubHighlightsList: 'epub-highlights:list',
    epubHighlightsCreate: 'epub-highlights:create',
    bookmarksList: 'bookmarks:list',
    bookmarksToggle: 'bookmarks:toggle',
    bookmarksRemove: 'bookmarks:remove',
    epubBookmarksList: 'epub-bookmarks:list',
    epubBookmarksToggle: 'epub-bookmarks:toggle',
    exportGetBookData: 'export:get-book-data',
    exportSaveFile: 'export:save-file',
    epubProgressGet: 'epub-progress:get',
    epubProgressSet: 'epub-progress:set',
    flowProgressGet: 'flow-progress:get',
    flowProgressSet: 'flow-progress:set',
    readerSettingsGet: 'reader-settings:get',
    readerSettingsUpdate: 'reader-settings:update',
    progressGetLastPage: 'progress:get-last-page',
    progressSetLastPage: 'progress:set-last-page',
    statsMarkOpened: 'stats:mark-opened',
    statsGetRecentBooks: 'stats:get-recent-books'
};
exports.READER_SETTINGS_DEFAULTS = {
    theme: 'light',
    epubFontSize: 100,
    epubLineHeight: 1.6,
    epubMargins: 'medium',
    epubFontFamily: 'serif',
    pdfBackground: 'light',
    pdfZoomPreset: 'fitWidth',
    dyslexiaFriendlyMode: false,
    highContrastMode: false,
    textSizePreset: 'normal',
    reduceMotion: false
};
